### ISSUE TITLE
Question about categorical inputs

### ISSUE THREAD

**Issue by cottrell** [Molecolab-Pisa/GPX#1]
I've just quickly skimmed the code so I might have missed something, but are you supporint mixed type inputs in any way, for example for features including both numeric and categorical values? I see what appears to be mostly X = ArrayLike requirements in the code. I've seen some other GP projects that require casting to float and back to deal with this.

**Comment by ecignoni** [comment]
Hi @cottrell, sorry for my late reply and thank you for your interest in GPX.

No, we do not have an explicit support for categorical variables (we don't deal with categorical variables in our daily work). I guess that casting to float and back looks like a viable solution.

If you need different kernels to deal with categorical variables, writing the kernel should be very easy since, if you don't care too much about performance, you can just write the kernel function for two inputs (what we call "kernel_base" in `kernels.py`), and feed that function to the `Kernel` class to have access to the full kernel and the derivative/hessian kernels, something along these lines:

```python
def categ_kernel_base(x1, x2, params, active_dims=None):
    # kernel implementation here
    return k12

class CategKernel(Kernel):
    def __init__(self, active_dims=None):
        self._kernel_base = categ_kernel_base
        super().__init__(active_dims)
```

and you should be good to go.
If you need faster functions you have to write them on your own, and you can take a look to `gpx/kernels/kernels.py` for some examples.
